import java.nio.file.Files
import java.nio.file.Path

tasks.register('listDependencies') {
    String gradleUserHomeDir = project.gradle.gradleUserHomeDir.toString()
    String buildDirectory = rootProject.layout.buildDirectory.get().toString()
    def runtimeClasspath = sourceSets.main.runtimeClasspath
    doLast {
        def prefix = Path.of(gradleUserHomeDir, 'caches', 'modules-2', 'files-2.1')
        def list = new ArrayList<String>()
        runtimeClasspath.forEach { f ->
            def path = f.toPath()
            if (path.startsWith(prefix)) {
                def relative = prefix.relativize(path)
                list.add("${relative.getName(0)}:${relative.getName(1)}:${relative.getName(2)}")
            }
        }
        list.sort()
        def dependenciesDir = Path.of(buildDirectory, 'dependencies')
        Files.createDirectories(dependenciesDir)
        def output = dependenciesDir.resolve('list.txt').toFile()
        output.write(list.join('\n'))
        println "Created " + output.toString()
    }
}
