/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import org.eclipse.openvsx.jooq.tables.CustomerMembership;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerMembershipRecord extends UpdatableRecordImpl<CustomerMembershipRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.customer_membership.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.customer_membership.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.customer_membership.customer</code>.
     */
    public void setCustomer(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.customer_membership.customer</code>.
     */
    public Long getCustomer() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.customer_membership.user_data</code>.
     */
    public void setUserData(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.customer_membership.user_data</code>.
     */
    public Long getUserData() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerMembershipRecord
     */
    public CustomerMembershipRecord() {
        super(CustomerMembership.CUSTOMER_MEMBERSHIP);
    }

    /**
     * Create a detached, initialised CustomerMembershipRecord
     */
    public CustomerMembershipRecord(Long id, Long customer, Long userData) {
        super(CustomerMembership.CUSTOMER_MEMBERSHIP);

        setId(id);
        setCustomer(customer);
        setUserData(userData);
        resetChangedOnNotNull();
    }
}
