/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import java.time.LocalDate;

import org.eclipse.openvsx.jooq.tables.DailyUsageStats;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DailyUsageStatsRecord extends UpdatableRecordImpl<DailyUsageStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.daily_usage_stats.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.daily_usage_stats.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.daily_usage_stats.customer_id</code>.
     */
    public void setCustomerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.daily_usage_stats.customer_id</code>.
     */
    public Long getCustomerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.daily_usage_stats.date</code>.
     */
    public void setDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.daily_usage_stats.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.daily_usage_stats.total_requests</code>.
     */
    public void setTotalRequests(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.daily_usage_stats.total_requests</code>.
     */
    public Long getTotalRequests() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.daily_usage_stats.p95_requests</code>.
     */
    public void setP95Requests(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.daily_usage_stats.p95_requests</code>.
     */
    public Long getP95Requests() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DailyUsageStatsRecord
     */
    public DailyUsageStatsRecord() {
        super(DailyUsageStats.DAILY_USAGE_STATS);
    }

    /**
     * Create a detached, initialised DailyUsageStatsRecord
     */
    public DailyUsageStatsRecord(Long id, Long customerId, LocalDate date, Long totalRequests, Long p95Requests) {
        super(DailyUsageStats.DAILY_USAGE_STATS);

        setId(id);
        setCustomerId(customerId);
        setDate(date);
        setTotalRequests(totalRequests);
        setP95Requests(p95Requests);
        resetChangedOnNotNull();
    }
}
