/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import java.time.LocalDateTime;

import org.eclipse.openvsx.jooq.tables.DownloadIngestion;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DownloadIngestionRecord extends UpdatableRecordImpl<DownloadIngestionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.download_ingestion.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.download_ingestion.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.download_ingestion.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.download_ingestion.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.download_ingestion.storage_type</code>.
     */
    public void setStorageType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.download_ingestion.storage_type</code>.
     */
    public String getStorageType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.download_ingestion.processed_on</code>.
     */
    public void setProcessedOn(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.download_ingestion.processed_on</code>.
     */
    public LocalDateTime getProcessedOn() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.download_ingestion.execution_time</code>.
     */
    public void setExecutionTime(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.download_ingestion.execution_time</code>.
     */
    public Integer getExecutionTime() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.download_ingestion.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.download_ingestion.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DownloadIngestionRecord
     */
    public DownloadIngestionRecord() {
        super(DownloadIngestion.DOWNLOAD_INGESTION);
    }

    /**
     * Create a detached, initialised DownloadIngestionRecord
     */
    public DownloadIngestionRecord(Long id, String name, String storageType, LocalDateTime processedOn, Integer executionTime, Boolean success) {
        super(DownloadIngestion.DOWNLOAD_INGESTION);

        setId(id);
        setName(name);
        setStorageType(storageType);
        setProcessedOn(processedOn);
        setExecutionTime(executionTime);
        setSuccess(success);
        resetChangedOnNotNull();
    }
}
