/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import java.time.LocalDateTime;

import org.eclipse.openvsx.jooq.tables.ExtensionSizeOverride;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExtensionSizeOverrideRecord extends UpdatableRecordImpl<ExtensionSizeOverrideRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.extension_size_override.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.extension_size_override.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.extension_size_override.scope_namespace_id</code>.
     */
    public void setScopeNamespaceId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.extension_size_override.scope_namespace_id</code>.
     */
    public Long getScopeNamespaceId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>public.extension_size_override.scope_extension_id</code>.
     */
    public void setScopeExtensionId(Long value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.extension_size_override.scope_extension_id</code>.
     */
    public Long getScopeExtensionId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.extension_size_override.max_size</code>.
     */
    public void setMaxSize(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.extension_size_override.max_size</code>.
     */
    public Long getMaxSize() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.extension_size_override.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.extension_size_override.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.extension_size_override.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.extension_size_override.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExtensionSizeOverrideRecord
     */
    public ExtensionSizeOverrideRecord() {
        super(ExtensionSizeOverride.EXTENSION_SIZE_OVERRIDE);
    }

    /**
     * Create a detached, initialised ExtensionSizeOverrideRecord
     */
    public ExtensionSizeOverrideRecord(Long id, Long scopeNamespaceId, Long scopeExtensionId, Long maxSize, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(ExtensionSizeOverride.EXTENSION_SIZE_OVERRIDE);

        setId(id);
        setScopeNamespaceId(scopeNamespaceId);
        setScopeExtensionId(scopeExtensionId);
        setMaxSize(maxSize);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
