/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import java.time.LocalDateTime;

import org.eclipse.openvsx.jooq.tables.RateLimitToken;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RateLimitTokenRecord extends UpdatableRecordImpl<RateLimitTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.rate_limit_token.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.rate_limit_token.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.rate_limit_token.customer</code>.
     */
    public void setCustomer(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.rate_limit_token.customer</code>.
     */
    public Long getCustomer() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.rate_limit_token.active</code>.
     */
    public void setActive(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.rate_limit_token.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.rate_limit_token.created_timestamp</code>.
     */
    public void setCreatedTimestamp(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.rate_limit_token.created_timestamp</code>.
     */
    public LocalDateTime getCreatedTimestamp() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.rate_limit_token.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.rate_limit_token.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.rate_limit_token.value</code>.
     */
    public void setValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.rate_limit_token.value</code>.
     */
    public String getValue() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RateLimitTokenRecord
     */
    public RateLimitTokenRecord() {
        super(RateLimitToken.RATE_LIMIT_TOKEN);
    }

    /**
     * Create a detached, initialised RateLimitTokenRecord
     */
    public RateLimitTokenRecord(Long id, Long customer, Boolean active, LocalDateTime createdTimestamp, String description, String value) {
        super(RateLimitToken.RATE_LIMIT_TOKEN);

        setId(id);
        setCustomer(customer);
        setActive(active);
        setCreatedTimestamp(createdTimestamp);
        setDescription(description);
        setValue(value);
        resetChangedOnNotNull();
    }
}
