/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import org.eclipse.openvsx.jooq.tables.UserDataPermission;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserDataPermissionRecord extends UpdatableRecordImpl<UserDataPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_data_permission.user_data_id</code>.
     */
    public void setUserDataId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_data_permission.user_data_id</code>.
     */
    public Long getUserDataId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_data_permission.permission</code>.
     */
    public void setPermission(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_data_permission.permission</code>.
     */
    public String getPermission() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDataPermissionRecord
     */
    public UserDataPermissionRecord() {
        super(UserDataPermission.USER_DATA_PERMISSION);
    }

    /**
     * Create a detached, initialised UserDataPermissionRecord
     */
    public UserDataPermissionRecord(Long userDataId, String permission) {
        super(UserDataPermission.USER_DATA_PERMISSION);

        setUserDataId(userDataId);
        setPermission(permission);
        resetChangedOnNotNull();
    }
}
