/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Indexes;
import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.CustomerMembershipRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerMembership extends TableImpl<CustomerMembershipRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.customer_membership</code>
     */
    public static final CustomerMembership CUSTOMER_MEMBERSHIP = new CustomerMembership();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerMembershipRecord> getRecordType() {
        return CustomerMembershipRecord.class;
    }

    /**
     * The column <code>public.customer_membership.id</code>.
     */
    public final TableField<CustomerMembershipRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.customer_membership.customer</code>.
     */
    public final TableField<CustomerMembershipRecord, Long> CUSTOMER = createField(DSL.name("customer"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.customer_membership.user_data</code>.
     */
    public final TableField<CustomerMembershipRecord, Long> USER_DATA = createField(DSL.name("user_data"), SQLDataType.BIGINT, this, "");

    private CustomerMembership(Name alias, Table<CustomerMembershipRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerMembership(Name alias, Table<CustomerMembershipRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.customer_membership</code> table reference
     */
    public CustomerMembership(String alias) {
        this(DSL.name(alias), CUSTOMER_MEMBERSHIP);
    }

    /**
     * Create an aliased <code>public.customer_membership</code> table reference
     */
    public CustomerMembership(Name alias) {
        this(alias, CUSTOMER_MEMBERSHIP);
    }

    /**
     * Create a <code>public.customer_membership</code> table reference
     */
    public CustomerMembership() {
        this(DSL.name("customer_membership"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CUSTOMER_MEMBERSHIP_NAMESPACE_IDX, Indexes.CUSTOMER_MEMBERSHIP_USER_DATA_IDX);
    }

    @Override
    public Identity<CustomerMembershipRecord, Long> getIdentity() {
        return (Identity<CustomerMembershipRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CustomerMembershipRecord> getPrimaryKey() {
        return Keys.CUSTOMER_MEMBERSHIP_PKEY;
    }

    @Override
    public List<ForeignKey<CustomerMembershipRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CUSTOMER_MEMBERSHIP__CUSTOMER_MEMBERSHIP_CUSTOMER_FK, Keys.CUSTOMER_MEMBERSHIP__CUSTOMER_MEMBERSHIP_USER_DATA_FK);
    }

    @Override
    public CustomerMembership as(String alias) {
        return new CustomerMembership(DSL.name(alias), this);
    }

    @Override
    public CustomerMembership as(Name alias) {
        return new CustomerMembership(alias, this);
    }

    @Override
    public CustomerMembership as(Table<?> alias) {
        return new CustomerMembership(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerMembership rename(String name) {
        return new CustomerMembership(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerMembership rename(Name name) {
        return new CustomerMembership(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerMembership rename(Table<?> name) {
        return new CustomerMembership(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerMembership where(Condition condition) {
        return new CustomerMembership(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerMembership where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerMembership where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerMembership where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerMembership where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerMembership where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerMembership where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerMembership where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerMembership whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerMembership whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
