/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.DailyUsageStatsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DailyUsageStats extends TableImpl<DailyUsageStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.daily_usage_stats</code>
     */
    public static final DailyUsageStats DAILY_USAGE_STATS = new DailyUsageStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DailyUsageStatsRecord> getRecordType() {
        return DailyUsageStatsRecord.class;
    }

    /**
     * The column <code>public.daily_usage_stats.id</code>.
     */
    public final TableField<DailyUsageStatsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.daily_usage_stats.customer_id</code>.
     */
    public final TableField<DailyUsageStatsRecord, Long> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.daily_usage_stats.date</code>.
     */
    public final TableField<DailyUsageStatsRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.daily_usage_stats.total_requests</code>.
     */
    public final TableField<DailyUsageStatsRecord, Long> TOTAL_REQUESTS = createField(DSL.name("total_requests"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.daily_usage_stats.p95_requests</code>.
     */
    public final TableField<DailyUsageStatsRecord, Long> P95_REQUESTS = createField(DSL.name("p95_requests"), SQLDataType.BIGINT.nullable(false), this, "");

    private DailyUsageStats(Name alias, Table<DailyUsageStatsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DailyUsageStats(Name alias, Table<DailyUsageStatsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.daily_usage_stats</code> table reference
     */
    public DailyUsageStats(String alias) {
        this(DSL.name(alias), DAILY_USAGE_STATS);
    }

    /**
     * Create an aliased <code>public.daily_usage_stats</code> table reference
     */
    public DailyUsageStats(Name alias) {
        this(alias, DAILY_USAGE_STATS);
    }

    /**
     * Create a <code>public.daily_usage_stats</code> table reference
     */
    public DailyUsageStats() {
        this(DSL.name("daily_usage_stats"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DailyUsageStatsRecord, Long> getIdentity() {
        return (Identity<DailyUsageStatsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DailyUsageStatsRecord> getPrimaryKey() {
        return Keys.DAILY_USAGE_STATS_PKEY;
    }

    @Override
    public List<UniqueKey<DailyUsageStatsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.DAILY_USAGE_STATS_UNIQUE_CUSTOMER_DATE);
    }

    @Override
    public List<ForeignKey<DailyUsageStatsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DAILY_USAGE_STATS__DAILY_USAGE_STATS_CUSTOMER_FK);
    }

    @Override
    public DailyUsageStats as(String alias) {
        return new DailyUsageStats(DSL.name(alias), this);
    }

    @Override
    public DailyUsageStats as(Name alias) {
        return new DailyUsageStats(alias, this);
    }

    @Override
    public DailyUsageStats as(Table<?> alias) {
        return new DailyUsageStats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DailyUsageStats rename(String name) {
        return new DailyUsageStats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DailyUsageStats rename(Name name) {
        return new DailyUsageStats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DailyUsageStats rename(Table<?> name) {
        return new DailyUsageStats(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyUsageStats where(Condition condition) {
        return new DailyUsageStats(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyUsageStats where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyUsageStats where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyUsageStats where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DailyUsageStats where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DailyUsageStats where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DailyUsageStats where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DailyUsageStats where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyUsageStats whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyUsageStats whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
