/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Indexes;
import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.DownloadIngestionRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DownloadIngestion extends TableImpl<DownloadIngestionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.download_ingestion</code>
     */
    public static final DownloadIngestion DOWNLOAD_INGESTION = new DownloadIngestion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DownloadIngestionRecord> getRecordType() {
        return DownloadIngestionRecord.class;
    }

    /**
     * The column <code>public.download_ingestion.id</code>.
     */
    public final TableField<DownloadIngestionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.download_ingestion.name</code>.
     */
    public final TableField<DownloadIngestionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.download_ingestion.storage_type</code>.
     */
    public final TableField<DownloadIngestionRecord, String> STORAGE_TYPE = createField(DSL.name("storage_type"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.download_ingestion.processed_on</code>.
     */
    public final TableField<DownloadIngestionRecord, LocalDateTime> PROCESSED_ON = createField(DSL.name("processed_on"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.download_ingestion.execution_time</code>.
     */
    public final TableField<DownloadIngestionRecord, Integer> EXECUTION_TIME = createField(DSL.name("execution_time"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.download_ingestion.success</code>.
     */
    public final TableField<DownloadIngestionRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private DownloadIngestion(Name alias, Table<DownloadIngestionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DownloadIngestion(Name alias, Table<DownloadIngestionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.download_ingestion</code> table reference
     */
    public DownloadIngestion(String alias) {
        this(DSL.name(alias), DOWNLOAD_INGESTION);
    }

    /**
     * Create an aliased <code>public.download_ingestion</code> table reference
     */
    public DownloadIngestion(Name alias) {
        this(alias, DOWNLOAD_INGESTION);
    }

    /**
     * Create a <code>public.download_ingestion</code> table reference
     */
    public DownloadIngestion() {
        this(DSL.name("download_ingestion"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DOWNLOAD_INGESTION_NAME, Indexes.DOWNLOAD_INGESTION_STORAGE_TYPE);
    }

    @Override
    public UniqueKey<DownloadIngestionRecord> getPrimaryKey() {
        return Keys.DOWNLOAD_INGESTION_PKEY;
    }

    @Override
    public DownloadIngestion as(String alias) {
        return new DownloadIngestion(DSL.name(alias), this);
    }

    @Override
    public DownloadIngestion as(Name alias) {
        return new DownloadIngestion(alias, this);
    }

    @Override
    public DownloadIngestion as(Table<?> alias) {
        return new DownloadIngestion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadIngestion rename(String name) {
        return new DownloadIngestion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadIngestion rename(Name name) {
        return new DownloadIngestion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadIngestion rename(Table<?> name) {
        return new DownloadIngestion(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadIngestion where(Condition condition) {
        return new DownloadIngestion(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadIngestion where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadIngestion where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadIngestion where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadIngestion where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadIngestion where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadIngestion where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadIngestion where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadIngestion whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadIngestion whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
