/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.ExtensionSizeOverrideRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExtensionSizeOverride extends TableImpl<ExtensionSizeOverrideRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.extension_size_override</code>
     */
    public static final ExtensionSizeOverride EXTENSION_SIZE_OVERRIDE = new ExtensionSizeOverride();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExtensionSizeOverrideRecord> getRecordType() {
        return ExtensionSizeOverrideRecord.class;
    }

    /**
     * The column <code>public.extension_size_override.id</code>.
     */
    public final TableField<ExtensionSizeOverrideRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public.extension_size_override.scope_namespace_id</code>.
     */
    public final TableField<ExtensionSizeOverrideRecord, Long> SCOPE_NAMESPACE_ID = createField(DSL.name("scope_namespace_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>public.extension_size_override.scope_extension_id</code>.
     */
    public final TableField<ExtensionSizeOverrideRecord, Long> SCOPE_EXTENSION_ID = createField(DSL.name("scope_extension_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.extension_size_override.max_size</code>.
     */
    public final TableField<ExtensionSizeOverrideRecord, Long> MAX_SIZE = createField(DSL.name("max_size"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.extension_size_override.created_at</code>.
     */
    public final TableField<ExtensionSizeOverrideRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.extension_size_override.updated_at</code>.
     */
    public final TableField<ExtensionSizeOverrideRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private ExtensionSizeOverride(Name alias, Table<ExtensionSizeOverrideRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ExtensionSizeOverride(Name alias, Table<ExtensionSizeOverrideRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.extension_size_override</code> table
     * reference
     */
    public ExtensionSizeOverride(String alias) {
        this(DSL.name(alias), EXTENSION_SIZE_OVERRIDE);
    }

    /**
     * Create an aliased <code>public.extension_size_override</code> table
     * reference
     */
    public ExtensionSizeOverride(Name alias) {
        this(alias, EXTENSION_SIZE_OVERRIDE);
    }

    /**
     * Create a <code>public.extension_size_override</code> table reference
     */
    public ExtensionSizeOverride() {
        this(DSL.name("extension_size_override"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ExtensionSizeOverrideRecord, Long> getIdentity() {
        return (Identity<ExtensionSizeOverrideRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ExtensionSizeOverrideRecord> getPrimaryKey() {
        return Keys.EXTENSION_SIZE_OVERRIDE_PKEY;
    }

    @Override
    public List<ForeignKey<ExtensionSizeOverrideRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EXTENSION_SIZE_OVERRIDE__EXTENSION_SIZE_OVERRIDE_SCOPE_EXTENSION_ID_FKEY, Keys.EXTENSION_SIZE_OVERRIDE__EXTENSION_SIZE_OVERRIDE_SCOPE_NAMESPACE_ID_FKEY);
    }

    @Override
    public ExtensionSizeOverride as(String alias) {
        return new ExtensionSizeOverride(DSL.name(alias), this);
    }

    @Override
    public ExtensionSizeOverride as(Name alias) {
        return new ExtensionSizeOverride(alias, this);
    }

    @Override
    public ExtensionSizeOverride as(Table<?> alias) {
        return new ExtensionSizeOverride(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionSizeOverride rename(String name) {
        return new ExtensionSizeOverride(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionSizeOverride rename(Name name) {
        return new ExtensionSizeOverride(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionSizeOverride rename(Table<?> name) {
        return new ExtensionSizeOverride(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionSizeOverride where(Condition condition) {
        return new ExtensionSizeOverride(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionSizeOverride where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionSizeOverride where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionSizeOverride where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionSizeOverride where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionSizeOverride where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionSizeOverride where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionSizeOverride where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionSizeOverride whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionSizeOverride whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
