/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Indexes;
import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.RateLimitTokenRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RateLimitToken extends TableImpl<RateLimitTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.rate_limit_token</code>
     */
    public static final RateLimitToken RATE_LIMIT_TOKEN = new RateLimitToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RateLimitTokenRecord> getRecordType() {
        return RateLimitTokenRecord.class;
    }

    /**
     * The column <code>public.rate_limit_token.id</code>.
     */
    public final TableField<RateLimitTokenRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.rate_limit_token.customer</code>.
     */
    public final TableField<RateLimitTokenRecord, Long> CUSTOMER = createField(DSL.name("customer"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.rate_limit_token.active</code>.
     */
    public final TableField<RateLimitTokenRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.rate_limit_token.created_timestamp</code>.
     */
    public final TableField<RateLimitTokenRecord, LocalDateTime> CREATED_TIMESTAMP = createField(DSL.name("created_timestamp"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.rate_limit_token.description</code>.
     */
    public final TableField<RateLimitTokenRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>public.rate_limit_token.value</code>.
     */
    public final TableField<RateLimitTokenRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(64), this, "");

    private RateLimitToken(Name alias, Table<RateLimitTokenRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RateLimitToken(Name alias, Table<RateLimitTokenRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.rate_limit_token</code> table reference
     */
    public RateLimitToken(String alias) {
        this(DSL.name(alias), RATE_LIMIT_TOKEN);
    }

    /**
     * Create an aliased <code>public.rate_limit_token</code> table reference
     */
    public RateLimitToken(Name alias) {
        this(alias, RATE_LIMIT_TOKEN);
    }

    /**
     * Create a <code>public.rate_limit_token</code> table reference
     */
    public RateLimitToken() {
        this(DSL.name("rate_limit_token"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RATE_LIMIT_TOKEN_CUSTOMER_IDX, Indexes.RATE_LIMIT_TOKEN_VALUE_IDX);
    }

    @Override
    public Identity<RateLimitTokenRecord, Long> getIdentity() {
        return (Identity<RateLimitTokenRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RateLimitTokenRecord> getPrimaryKey() {
        return Keys.RATE_LIMIT_TOKEN_PKEY;
    }

    @Override
    public List<ForeignKey<RateLimitTokenRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RATE_LIMIT_TOKEN__RATE_LIMIT_TOKEN_CUSTOMER_FK);
    }

    @Override
    public RateLimitToken as(String alias) {
        return new RateLimitToken(DSL.name(alias), this);
    }

    @Override
    public RateLimitToken as(Name alias) {
        return new RateLimitToken(alias, this);
    }

    @Override
    public RateLimitToken as(Table<?> alias) {
        return new RateLimitToken(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RateLimitToken rename(String name) {
        return new RateLimitToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RateLimitToken rename(Name name) {
        return new RateLimitToken(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RateLimitToken rename(Table<?> name) {
        return new RateLimitToken(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RateLimitToken where(Condition condition) {
        return new RateLimitToken(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RateLimitToken where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RateLimitToken where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RateLimitToken where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RateLimitToken where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RateLimitToken where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RateLimitToken where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RateLimitToken where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RateLimitToken whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RateLimitToken whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
