/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.UserDataPermissionRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserDataPermission extends TableImpl<UserDataPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_data_permission</code>
     */
    public static final UserDataPermission USER_DATA_PERMISSION = new UserDataPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserDataPermissionRecord> getRecordType() {
        return UserDataPermissionRecord.class;
    }

    /**
     * The column <code>public.user_data_permission.user_data_id</code>.
     */
    public final TableField<UserDataPermissionRecord, Long> USER_DATA_ID = createField(DSL.name("user_data_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_data_permission.permission</code>.
     */
    public final TableField<UserDataPermissionRecord, String> PERMISSION = createField(DSL.name("permission"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    private UserDataPermission(Name alias, Table<UserDataPermissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserDataPermission(Name alias, Table<UserDataPermissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_data_permission</code> table
     * reference
     */
    public UserDataPermission(String alias) {
        this(DSL.name(alias), USER_DATA_PERMISSION);
    }

    /**
     * Create an aliased <code>public.user_data_permission</code> table
     * reference
     */
    public UserDataPermission(Name alias) {
        this(alias, USER_DATA_PERMISSION);
    }

    /**
     * Create a <code>public.user_data_permission</code> table reference
     */
    public UserDataPermission() {
        this(DSL.name("user_data_permission"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UserDataPermissionRecord> getPrimaryKey() {
        return Keys.USER_DATA_PERMISSION_PKEY;
    }

    @Override
    public List<ForeignKey<UserDataPermissionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_DATA_PERMISSION__USER_DATA_PERMISSION_FKEY);
    }

    @Override
    public UserDataPermission as(String alias) {
        return new UserDataPermission(DSL.name(alias), this);
    }

    @Override
    public UserDataPermission as(Name alias) {
        return new UserDataPermission(alias, this);
    }

    @Override
    public UserDataPermission as(Table<?> alias) {
        return new UserDataPermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDataPermission rename(String name) {
        return new UserDataPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDataPermission rename(Name name) {
        return new UserDataPermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDataPermission rename(Table<?> name) {
        return new UserDataPermission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDataPermission where(Condition condition) {
        return new UserDataPermission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDataPermission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDataPermission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDataPermission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDataPermission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDataPermission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDataPermission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDataPermission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDataPermission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDataPermission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
