apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: openvsx
  labels:
    app.kubernetes.io/name: openvsx
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  # base64 encoded values — replace with your own
  # echo -n 'openvsx' | base64
  database: b3BlbnZzeA==
  username: b3BlbnZzeA==
  password: b3BlbnZzeA==
---
apiVersion: v1
kind: Secret
metadata:
  name: ovsx-pat
  namespace: openvsx
  labels:
    app.kubernetes.io/name: openvsx
    app.kubernetes.io/component: ovsx-cli
type: Opaque
data:
  # base64 encoded value — replace with your own
  token: ""
